// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klcfyohkhmhmuisiawjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsY2Z5b2hraG1obXVpc2lhd2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyMzc3ODksImV4cCI6MjA0ODgxMzc4OX0.CwiaGbF1Pbrk5OfrQGs34gM11voCjQTWKN5qPpq_FmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);